INSERT INTO tags (ID, TAG, DESCRICAO) VALUES ('1', 'TESTE1', 'DECRICAO');
INSERT INTO tags (ID, TAG,DESCRICAO) VALUES ('2', 'TESTE2', 'DECRICAO');
INSERT INTO tags (ID, TAG, DESCRICAO) VALUES ('3', 'TESTE3', 'DECRICAO');